// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const LOADING_USER = 'LOADING_USER';
export const STOP_LOADING_USER = 'STOP_LOADING_USER';
export const SIGNING_UP_USER = 'SIGNING_UP_USER';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// UI reducer types

export const SET_ERRORS_INFO_SENT = 'SET_ERRORS_INFO_SENT';
export const SET_ERRORS_TICKET_SENT = 'SET_ERRORS_INFO_SENT';
export const SET_ERRORS_TICKET_REPLY = 'SET_ERRORS_INFO_REPLY';
export const LOADING_UI = 'LOADING_UI';
export const NAVIGATE_SCREEN = "NAVIGATE_SCREEN";
export const CLEAR_ERRORS_INFO = 'CLEAR_ERRORS_INFO';
export const CLEAR_ERRORS_TICKET = 'CLEAR_ERRORS_TICKET';
export const CLEAR_ERRORS_TICKET_REPLY = 'CLEAR_ERRORS_TICKET_REPLY';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types

export const SET_GYM_DATA = 'SET_DATA';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_UNLOAD = 'PROFILE_UNLOAD';
export const SET_GYM_LIST_DATA = 'SET_GYM_LIST_DATA' ;
export const PRESSED_GYM = 'PRESSED_GYM' ;
export const SET_SUBSCRIBED_GYMS = "SET_CURRENT_GYM";
export const SET_SELECTED_TICKET = "SET_SELECTED_TICKET";
export const LOADED_DATA = "LOADED_DATA";
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_TICKETS_LOG = 'FETCH_USER_TICKETS_LOG';
export const TICKET_LOG_LOAD = 'TICKET_LOG_LOAD';
export const FETCH_USER_PLAN = 'FETCH_USER_PLAN';
export const FETCH_USER_PROFILE_PIC = 'FETCH_USER_PROFILE_PIC';
export const SET_FOOD_LIST_DATA = 'SET_FOOD_LIST_DATA' ;
export const SET_SEARCHED_LIST_DATA = 'SET_SEARCHED_LIST_DATA' ;

export const SENDING_INFOS = 'SENDING_INFOS';
export const INFO_SENT = 'INFO_SENT';
export const TICKET_SENT = 'TICKET_SENT';
export const TICKET_REPLY_SENT = 'TICKET_REPLY_SENT';
export const TICKET_REPLY_CLOSED = 'TICKET_REPLY_CLOSED';
export const USER_PLAN_RECIEVED = 'INFO_SENT';
export const INFO_SENT_DONE = 'INFO_SENT_DONE';
export const PRESSED_EXERCISE = 'PRESSED_EXERCISE' ;
export const PRESSED_MOVE = 'PRESSED_MOVE' ;
export const SET_MOVE_DATA='SET_MOVE_DATA' ;
